name: .NET Build and Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch || github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: |
        dotnet publish -c Release -r win-x64
        dotnet publish -c Release -r linux-x64
        dotnet publish -c Release -r osx-x64
        dotnet publish -c Release -r osx-arm64

    - name: Zip Artifacts
      run: |
        cd /home/runner/work/myrient-downloader/myrient-downloader/MyrientDownloader/bin/Release/net9.0
        zip -r MyrientDownloader-win-x64.zip win-x64/publish/*
        zip -r MyrientDownloader-linux-x64.zip linux-x64/publish/*
        zip -r MyrientDownloader-osx-x64.zip osx-x64/publish/*
        zip -r MyrientDownloader-osx-arm64.zip osx-arm64/publish/*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/MyrientDownloader-win-x64.zip
          **/MyrientDownloader-linux-x64.zip
          **/MyrientDownloader-osx-x64.zip
          **/MyrientDownloader-osx-arm64.zip
          LICENSE
      
