name: .NET Build and Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Specify a tag name to use for the workflow'
        required: false
        type: string
        default: ''
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get tag name
      id: get_tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          if [[ -z "$TAG_NAME" ]]; then
            echo "No tag name provided via workflow_dispatch input."
            # Optionally, handle this case, e.g., exit or use a default
          fi
        else # This is a push event
          TAG_NAME="${{ github.ref_name }}"
        fi
        echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
    
    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_tag.outputs.tag_name }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --configuration Release -o publish
