name: .NET Build and Tag

on:
  workflow_dispatch:
    inputs:
      target_tag:
        required: true
        type: string
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch || github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: |
        dotnet publish -c Release -r win-x64
        dotnet publish -c Release -r linux-x64
        dotnet publish -c Release -r osx-x64
        dotnet publish -c Release -r osx-arm
